Update sync-image-example.yml

diff --git a/.github/workflows/sync-image-example.yml b/.github/workflows/sync-image-example.yml
--- a/.github/workflows/sync-image-example.yml
+++ b/.github/workflows/sync-image-example.yml
@@ -1,4 +1,4 @@
-name: Sync Image to Aliyun  Example
+name: Sync Image to Aliyun
 
 on:
   push:
@@ -17,17 +17,25 @@ jobs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2.9.1
 
-    - name: Login to Docker Hub
+    - name: Login to Aliyun Container Registry
       uses: docker/login-action@v2.2.0
       with:
         registry: registry.cn-hangzhou.aliyuncs.com
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
-        logout: false
+
+    - name: Install Skopeo
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y skopeo
 
     - name: Use Skopeo Tools Sync Image to Docker Hub
       run: |
-         skopeo copy docker://docker.io/userxy2015/ngnix:latest docker://registry.cn-hangzhou.aliyuncs.com/xzm_docker/nginx-image/ngnix:latest
-         
-         
-         
+        skopeo copy docker://docker.io/userxy2015/ngnix:latest docker://registry.cn-hangzhou.aliyuncs.com/xzm_docker/nginx-image/ngnix:latest
+      continue-on-error: true  # This will allow the workflow to continue even if this step fails
+
+    - name: Check if previous step failed
+      if: failure()
+      run: |
+        echo "Failed to sync image with Skopeo"
+        exit 1
